[package]
name = "test-project"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.44.1", features = ["full", "rt-multi-thread"]}
reqwest = { version = "0.12.10", features = ["json"] }
